spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forecnu?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
  #     Redis服务器连接密码（默认为空）
  #    password: 123456


#配置mybatis的mapper映射文件地址
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

